### PR TITLE
Expand machine configuration with av96-root-files

### PR DESCRIPTION
**Pull request by ghost**
Add av96-root-files package to the image via
MACHINE_EXTRA_RRECOMMENDS.
The package is not essential for boot but contains
important firmware images.

Signed-off-by: Zbigniew Bodek <zbigniew.bodek@huawei.com>

### CODE REVIEW

**Comment by ghost** [comment]
@bkardosa @mschmoeller 
Hi, I would be grateful if you could take a look at this Pull Request, send your comments and if there is none, please merge.

**Comment by bkardosa** [comment]
Could you please clarify why this is needed?

**Comment by ghost** [comment]
> Could you please clarify why this is needed?

Building image for avenger without `av96-root-files` package makes no sense because we won't have the required firmware. This change allows us to take any distro and image and build it without explicitly including `av96-root-files` in `local.conf` or anywhere else and still have those files included as long as we specify `MACHINE=stm32mp1-av96`

**Comment by ghost** [comment]
Just to further clarify, this change is more a workaround to allow us to pull crucial firmware files from `av96-root-files` by just specifying `MACHINE=stm32mp1-av96` but `av96-root-files` also pulls a lot of unnecessary files that we do not want to incorporate in our images. In the following changes we want to separate those crucial BSP files from other, unrelated configuration files, scripts, etc. and "EXTRA RRECOMMEND" only the BSP part.
Please keep that in mind.

**Comment by ghost** [comment]
This pull request was already resolved as a part of other change https://github.com/dh-electronics/meta-av96/commit/9d2a3fdacf49aebc9298a7c444f5a021d3e99e13

**Pull request closed without merging**
